import 'package:flutter/material.dart';

class Material3Color extends ColorSwatch<int> {
  /// Creates a color swatch with a variety of shades.
  ///
  /// The `primary` argument should be the 32 bit ARGB value of one of the
  /// values in the swatch, as would be passed to the [Color.new] constructor
  /// for that same color, and as is exposed by [value]. (This is distinct from
  /// the specific index of the color in the swatch.)
  const Material3Color(super.primary, super.swatch);

  /// Pure Black.
  Color get shade0 => this[0]!;

  /// The darkest shade.
  Color get shade10 => this[10]!;

  /// The second darkest shade.
  Color get shade20 => this[20]!;

  /// The third darkest shade.
  Color get shade30 => this[30]!;

  /// The default shade.
  Color get shade40 => this[40]!;

  /// The fifth darkest shade.
  Color get shade50 => this[50]!;

  /// The sixth darkest shade.
  Color get shade60 => this[60]!;

  /// The sixth lightest shade.
  Color get shade70 => this[70]!;

  /// The fifth lightest shade.
  Color get shade80 => this[80]!;

  /// The fourth lightest shade.
  Color get shade90 => this[90]!;

  /// The third lightest shade.
  Color get shade95 => this[95]!;

  /// The second lightest shade.
  Color get shade98 => this[98]!;

  /// The lightest shade.
  Color get shade99 => this[99]!;

  /// Pure White.
  Color get shade100 => this[100]!;
}

/// Work in progress
class Material3Theme {
  final Material3Color primary;
  final Material3Color secondary;
  final Material3Color tertiary;
  final Material3Color error;
  final Material3Color neutral;
  final Material3Color neutralVariant;

  const Material3Theme({
    required this.primary,
    required this.secondary,
    required this.tertiary,
    required this.error,
    required this.neutral,
    required this.neutralVariant,
  });
}

class Material3Schemes {
  final ColorScheme light;
  final ColorScheme dark;

  const Material3Schemes({required this.light, required this.dark});
}

class ThemeSchemes {
  const ThemeSchemes._();

  static const red = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFBB1614),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFDAD5),
      onPrimaryContainer: Color(0xFF410001),
      secondary: Color(0xFF775652),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFFDAD5),
      onSecondaryContainer: Color(0xFF2C1512),
      tertiary: Color(0xFF705C2E),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFCDFA6),
      onTertiaryContainer: Color(0xFF261A00),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFFFBFF),
      onBackground: Color(0xFF201A19),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF201A19),
      surfaceVariant: Color(0xFFF5DDDA),
      onSurfaceVariant: Color(0xFF534341),
      outline: Color(0xFF857370),
      onInverseSurface: Color(0xFFFBEEEC),
      inverseSurface: Color(0xFF362F2E),
      inversePrimary: Color(0xFFFFB4A9),
      shadow: Colors.black12,
      surfaceTint: Color(0xFFBB1614),
      // outlineVariant: Color(0xFFD8C2BE),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFB4A9),
      onPrimary: Color(0xFF690002),
      primaryContainer: Color(0xFF930005),
      onPrimaryContainer: Color(0xFFFFDAD5),
      secondary: Color(0xFFE7BDB7),
      onSecondary: Color(0xFF442926),
      secondaryContainer: Color(0xFF5D3F3B),
      onSecondaryContainer: Color(0xFFFFDAD5),
      tertiary: Color(0xFFDFC38C),
      onTertiary: Color(0xFF3E2E04),
      tertiaryContainer: Color(0xFF574419),
      onTertiaryContainer: Color(0xFFFCDFA6),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF201A19),
      onBackground: Color(0xFFEDE0DE),
      surface: Color(0xFF201A19),
      onSurface: Color(0xFFEDE0DE),
      surfaceVariant: Color(0xFF534341),
      onSurfaceVariant: Color(0xFFD8C2BE),
      outline: Color(0xFFA08C89),
      onInverseSurface: Color(0xFF201A19),
      inverseSurface: Color(0xFFEDE0DE),
      inversePrimary: Color(0xFFBB1614),
      shadow: Colors.black12,
      surfaceTint: Color(0xFFFFB4A9),
      // outlineVariant: Color(0xFF534341),
      // scrim: Color(0xFF000000),
    ),
  );

  static const pink = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFBC004B),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFD9DE),
      onPrimaryContainer: Color(0xFF400014),
      secondary: Color(0xFF75565B),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFFD9DE),
      onSecondaryContainer: Color(0xFF2C1519),
      tertiary: Color(0xFF795831),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFDDBA),
      onTertiaryContainer: Color(0xFF2B1700),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFFFBFF),
      onBackground: Color(0xFF201A1B),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF201A1B),
      surfaceVariant: Color(0xFFF3DDDF),
      onSurfaceVariant: Color(0xFF524345),
      outline: Color(0xFF847375),
      onInverseSurface: Color(0xFFFBEEEE),
      inverseSurface: Color(0xFF362F2F),
      inversePrimary: Color(0xFFFFB2BE),
      shadow: Colors.black12,
      surfaceTint: Color(0xFFBC004B),
      // outlineVariant: Color(0xFFD6C2C3),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFB2BE),
      onPrimary: Color(0xFF660025),
      primaryContainer: Color(0xFF900038),
      onPrimaryContainer: Color(0xFFFFD9DE),
      secondary: Color(0xFFE5BDC2),
      onSecondary: Color(0xFF43292D),
      secondaryContainer: Color(0xFF5C3F43),
      onSecondaryContainer: Color(0xFFFFD9DE),
      tertiary: Color(0xFFEBBF90),
      onTertiary: Color(0xFF452B08),
      tertiaryContainer: Color(0xFF5F411C),
      onTertiaryContainer: Color(0xFFFFDDBA),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF201A1B),
      onBackground: Color(0xFFECE0E0),
      surface: Color(0xFF201A1B),
      onSurface: Color(0xFFECE0E0),
      surfaceVariant: Color(0xFF524345),
      onSurfaceVariant: Color(0xFFD6C2C3),
      outline: Color(0xFF9F8C8E),
      onInverseSurface: Color(0xFF201A1B),
      inverseSurface: Color(0xFFECE0E0),
      inversePrimary: Color(0xFFBC004B),
      shadow: Colors.black12,
      surfaceTint: Color(0xFFFFB2BE),
      // outlineVariant: Color(0xFF524345),
      // scrim: Color(0xFF000000),
    ),
  );

  static const purple = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF9A25AE),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFD6FE),
      onPrimaryContainer: Color(0xFF35003F),
      secondary: Color(0xFF6B586B),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFF4DBF1),
      onSecondaryContainer: Color(0xFF251626),
      tertiary: Color(0xFF82524A),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFDAD4),
      onTertiaryContainer: Color(0xFF33110C),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFFFBFF),
      onBackground: Color(0xFF1E1A1D),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF1E1A1D),
      surfaceVariant: Color(0xFFECDFE8),
      onSurfaceVariant: Color(0xFF4D444C),
      outline: Color(0xFF7F747D),
      onInverseSurface: Color(0xFFF7EEF3),
      inverseSurface: Color(0xFF332F32),
      inversePrimary: Color(0xFFF9ABFF),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF9A25AE),
      // outlineVariant: Color(0xFFD0C3CC),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFF9ABFF),
      onPrimary: Color(0xFF570066),
      primaryContainer: Color(0xFF7B008F),
      onPrimaryContainer: Color(0xFFFFD6FE),
      secondary: Color(0xFFD7BFD5),
      onSecondary: Color(0xFF3B2B3C),
      secondaryContainer: Color(0xFF534153),
      onSecondaryContainer: Color(0xFFF4DBF1),
      tertiary: Color(0xFFF6B8AD),
      onTertiary: Color(0xFF4C251F),
      tertiaryContainer: Color(0xFF673B34),
      onTertiaryContainer: Color(0xFFFFDAD4),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF1E1A1D),
      onBackground: Color(0xFFE9E0E4),
      surface: Color(0xFF1E1A1D),
      onSurface: Color(0xFFE9E0E4),
      surfaceVariant: Color(0xFF4D444C),
      onSurfaceVariant: Color(0xFFD0C3CC),
      outline: Color(0xFF998D96),
      onInverseSurface: Color(0xFF1E1A1D),
      inverseSurface: Color(0xFFE9E0E4),
      inversePrimary: Color(0xFF9A25AE),
      shadow: Colors.black12,
      surfaceTint: Color(0xFFF9ABFF),
      // outlineVariant: Color(0xFF4D444C),
      // scrim: Color(0xFF000000),
    ),
  );

  static const deepPurple = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF6F43C0),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFEBDDFF),
      onPrimaryContainer: Color(0xFF250059),
      secondary: Color(0xFF635B70),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFE9DEF8),
      onSecondaryContainer: Color(0xFF1F182B),
      tertiary: Color(0xFF7E525D),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFD9E1),
      onTertiaryContainer: Color(0xFF31101B),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFFFBFF),
      onBackground: Color(0xFF1D1B1E),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF1D1B1E),
      surfaceVariant: Color(0xFFE7E0EB),
      onSurfaceVariant: Color(0xFF49454E),
      outline: Color(0xFF7A757F),
      onInverseSurface: Color(0xFFF5EFF4),
      inverseSurface: Color(0xFF323033),
      inversePrimary: Color(0xFFD3BBFF),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF6F43C0),
      // outlineVariant: Color(0xFFCBC4CF),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFF9ABFF),
      onPrimary: Color(0xFF570066),
      primaryContainer: Color(0xFF7B008F),
      onPrimaryContainer: Color(0xFFFFD6FE),
      secondary: Color(0xFFD7BFD5),
      onSecondary: Color(0xFF3B2B3C),
      secondaryContainer: Color(0xFF534153),
      onSecondaryContainer: Color(0xFFF4DBF1),
      tertiary: Color(0xFFF6B8AD),
      onTertiary: Color(0xFF4C251F),
      tertiaryContainer: Color(0xFF673B34),
      onTertiaryContainer: Color(0xFFFFDAD4),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF1E1A1D),
      onBackground: Color(0xFFE9E0E4),
      surface: Color(0xFF1E1A1D),
      onSurface: Color(0xFFE9E0E4),
      surfaceVariant: Color(0xFF4D444C),
      onSurfaceVariant: Color(0xFFD0C3CC),
      outline: Color(0xFF998D96),
      onInverseSurface: Color(0xFF1E1A1D),
      inverseSurface: Color(0xFFE9E0E4),
      inversePrimary: Color(0xFF9A25AE),
      shadow: Colors.black12,
      surfaceTint: Color(0xFFF9ABFF),
      // outlineVariant: Color(0xFF4D444C),
      // scrim: Color(0xFF000000),
    ),
  );

  static const indigo = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF4355B9),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFDEE0FF),
      onPrimaryContainer: Color(0xFF00105C),
      secondary: Color(0xFF5B5D72),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFE0E1F9),
      onSecondaryContainer: Color(0xFF181A2C),
      tertiary: Color(0xFF77536D),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFFFD7F1),
      onTertiaryContainer: Color(0xFF2D1228),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFEFBFF),
      onBackground: Color(0xFF1B1B1F),
      surface: Color(0xFFFEFBFF),
      onSurface: Color(0xFF1B1B1F),
      surfaceVariant: Color(0xFFE3E1EC),
      onSurfaceVariant: Color(0xFF46464F),
      outline: Color(0xFF767680),
      onInverseSurface: Color(0xFFF3F0F4),
      inverseSurface: Color(0xFF303034),
      inversePrimary: Color(0xFFBAC3FF),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF4355B9),
      // outlineVariant: Color(0xFFC7C5D0),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFBAC3FF),
      onPrimary: Color(0xFF08218A),
      primaryContainer: Color(0xFF293CA0),
      onPrimaryContainer: Color(0xFFDEE0FF),
      secondary: Color(0xFFC3C5DD),
      onSecondary: Color(0xFF2D2F42),
      secondaryContainer: Color(0xFF434659),
      onSecondaryContainer: Color(0xFFE0E1F9),
      tertiary: Color(0xFFE6BAD7),
      onTertiary: Color(0xFF44263D),
      tertiaryContainer: Color(0xFF5D3C55),
      onTertiaryContainer: Color(0xFFFFD7F1),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF1B1B1F),
      onBackground: Color(0xFFE4E1E6),
      surface: Color(0xFF1B1B1F),
      onSurface: Color(0xFFE4E1E6),
      surfaceVariant: Color(0xFF46464F),
      onSurfaceVariant: Color(0xFFC7C5D0),
      outline: Color(0xFF90909A),
      onInverseSurface: Color(0xFF1B1B1F),
      inverseSurface: Color(0xFFE4E1E6),
      inversePrimary: Color(0xFF4355B9),
      shadow: Colors.black12,
      surfaceTint: Color(0xFFBAC3FF),
      // scrim: Color(0xFF000000),
      // outlineVariant: Color(0xFF46464F),
    ),
  );

  static const blue = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF0061A4),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFD1E4FF),
      onPrimaryContainer: Color(0xFF001D36),
      secondary: Color(0xFF535F70),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFD7E3F7),
      onSecondaryContainer: Color(0xFF101C2B),
      tertiary: Color(0xFF6B5778),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFF2DAFF),
      onTertiaryContainer: Color(0xFF251431),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFDFCFF),
      onBackground: Color(0xFF1A1C1E),
      surface: Color(0xFFFDFCFF),
      onSurface: Color(0xFF1A1C1E),
      surfaceVariant: Color(0xFFDFE2EB),
      onSurfaceVariant: Color(0xFF43474E),
      outline: Color(0xFF73777F),
      onInverseSurface: Color(0xFFF1F0F4),
      inverseSurface: Color(0xFF2F3033),
      inversePrimary: Color(0xFF9ECAFF),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF0061A4),
      // outlineVariant: Color(0xFFC3C7CF),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF9ECAFF),
      onPrimary: Color(0xFF003258),
      primaryContainer: Color(0xFF00497D),
      onPrimaryContainer: Color(0xFFD1E4FF),
      secondary: Color(0xFFBBC7DB),
      onSecondary: Color(0xFF253140),
      secondaryContainer: Color(0xFF3B4858),
      onSecondaryContainer: Color(0xFFD7E3F7),
      tertiary: Color(0xFFD6BEE4),
      onTertiary: Color(0xFF3B2948),
      tertiaryContainer: Color(0xFF523F5F),
      onTertiaryContainer: Color(0xFFF2DAFF),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF1A1C1E),
      onBackground: Color(0xFFE2E2E6),
      surface: Color(0xFF1A1C1E),
      onSurface: Color(0xFFE2E2E6),
      surfaceVariant: Color(0xFF43474E),
      onSurfaceVariant: Color(0xFFC3C7CF),
      outline: Color(0xFF8D9199),
      onInverseSurface: Color(0xFF1A1C1E),
      inverseSurface: Color(0xFFE2E2E6),
      inversePrimary: Color(0xFF0061A4),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF9ECAFF),
      // outlineVariant: Color(0xFF43474E),
      // scrim: Color(0xFF000000),
    ),
  );

  static const lightBlue = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF006493),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFCAE6FF),
      onPrimaryContainer: Color(0xFF001E30),
      secondary: Color(0xFF50606E),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFD3E5F5),
      onSecondaryContainer: Color(0xFF0C1D29),
      tertiary: Color(0xFF65587B),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFEBDDFF),
      onTertiaryContainer: Color(0xFF201634),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFCFCFF),
      onBackground: Color(0xFF1A1C1E),
      surface: Color(0xFFFCFCFF),
      onSurface: Color(0xFF1A1C1E),
      surfaceVariant: Color(0xFFDDE3EA),
      onSurfaceVariant: Color(0xFF41474D),
      outline: Color(0xFF72787E),
      onInverseSurface: Color(0xFFF0F0F3),
      inverseSurface: Color(0xFF2E3133),
      inversePrimary: Color(0xFF8DCDFF),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF006493),
      // outlineVariant: Color(0xFFC1C7CE),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF8DCDFF),
      onPrimary: Color(0xFF00344F),
      primaryContainer: Color(0xFF004B70),
      onPrimaryContainer: Color(0xFFCAE6FF),
      secondary: Color(0xFFB7C9D9),
      onSecondary: Color(0xFF22323F),
      secondaryContainer: Color(0xFF384956),
      onSecondaryContainer: Color(0xFFD3E5F5),
      tertiary: Color(0xFFCFC0E8),
      onTertiary: Color(0xFF362B4B),
      tertiaryContainer: Color(0xFF4D4162),
      onTertiaryContainer: Color(0xFFEBDDFF),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF1A1C1E),
      onBackground: Color(0xFFE2E2E5),
      surface: Color(0xFF1A1C1E),
      onSurface: Color(0xFFE2E2E5),
      surfaceVariant: Color(0xFF41474D),
      onSurfaceVariant: Color(0xFFC1C7CE),
      outline: Color(0xFF8B9198),
      onInverseSurface: Color(0xFF1A1C1E),
      inverseSurface: Color(0xFFE2E2E5),
      inversePrimary: Color(0xFF006493),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF8DCDFF),
      // outlineVariant: Color(0xFF41474D),
      // scrim: Color(0xFF000000),
    ),
  );

  static const cyan = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF006876),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFA1EFFF),
      onPrimaryContainer: Color(0xFF001F25),
      secondary: Color(0xFF4A6268),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFCDE7ED),
      onSecondaryContainer: Color(0xFF051F23),
      tertiary: Color(0xFF545D7E),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFDBE1FF),
      onTertiaryContainer: Color(0xFF101A37),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFBFCFD),
      onBackground: Color(0xFF191C1D),
      surface: Color(0xFFFBFCFD),
      onSurface: Color(0xFF191C1D),
      surfaceVariant: Color(0xFFDBE4E6),
      onSurfaceVariant: Color(0xFF3F484A),
      outline: Color(0xFF6F797B),
      onInverseSurface: Color(0xFFEFF1F2),
      inverseSurface: Color(0xFF2E3132),
      inversePrimary: Color(0xFF44D8F1),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF006876),
      // outlineVariant: Color(0xFFBFC8CA),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF44D8F1),
      onPrimary: Color(0xFF00363E),
      primaryContainer: Color(0xFF004E59),
      onPrimaryContainer: Color(0xFFA1EFFF),
      secondary: Color(0xFFB1CBD1),
      onSecondary: Color(0xFF1C3439),
      secondaryContainer: Color(0xFF334A50),
      onSecondaryContainer: Color(0xFFCDE7ED),
      tertiary: Color(0xFFBCC5EB),
      onTertiary: Color(0xFF262F4D),
      tertiaryContainer: Color(0xFF3C4665),
      onTertiaryContainer: Color(0xFFDBE1FF),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF191C1D),
      onBackground: Color(0xFFE1E3E3),
      surface: Color(0xFF191C1D),
      onSurface: Color(0xFFE1E3E3),
      surfaceVariant: Color(0xFF3F484A),
      onSurfaceVariant: Color(0xFFBFC8CA),
      outline: Color(0xFF899295),
      onInverseSurface: Color(0xFF191C1D),
      inverseSurface: Color(0xFFE1E3E3),
      inversePrimary: Color(0xFF006876),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF44D8F1),
      // outlineVariant: Color(0xFF3F484A),
      // scrim: Color(0xFF000000),
    ),
  );

  static const teal = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF006A60),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFF74F8E5),
      onPrimaryContainer: Color(0xFF00201C),
      secondary: Color(0xFF4A635F),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFCCE8E2),
      onSecondaryContainer: Color(0xFF05201C),
      tertiary: Color(0xFF456179),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFCCE5FF),
      onTertiaryContainer: Color(0xFF001E31),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFAFDFB),
      onBackground: Color(0xFF191C1B),
      surface: Color(0xFFFAFDFB),
      onSurface: Color(0xFF191C1B),
      surfaceVariant: Color(0xFFDAE5E1),
      onSurfaceVariant: Color(0xFF3F4947),
      outline: Color(0xFF6F7977),
      onInverseSurface: Color(0xFFEFF1EF),
      inverseSurface: Color(0xFF2D3130),
      inversePrimary: Color(0xFF53DBC9),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF006A60),
      // outlineVariant: Color(0xFFBEC9C6),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF53DBC9),
      onPrimary: Color(0xFF003731),
      primaryContainer: Color(0xFF005048),
      onPrimaryContainer: Color(0xFF74F8E5),
      secondary: Color(0xFFB1CCC6),
      onSecondary: Color(0xFF1C3531),
      secondaryContainer: Color(0xFF334B47),
      onSecondaryContainer: Color(0xFFCCE8E2),
      tertiary: Color(0xFFADCAE6),
      onTertiary: Color(0xFF153349),
      tertiaryContainer: Color(0xFF2D4961),
      onTertiaryContainer: Color(0xFFCCE5FF),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF191C1B),
      onBackground: Color(0xFFE0E3E1),
      surface: Color(0xFF191C1B),
      onSurface: Color(0xFFE0E3E1),
      surfaceVariant: Color(0xFF3F4947),
      onSurfaceVariant: Color(0xFFBEC9C6),
      outline: Color(0xFF899390),
      onInverseSurface: Color(0xFF191C1B),
      inverseSurface: Color(0xFFE0E3E1),
      inversePrimary: Color(0xFF006A60),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF53DBC9),
      // outlineVariant: Color(0xFF3F4947),
      // scrim: Color(0xFF000000),
    ),
  );

  static const green = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF006E1C),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFF94F990),
      onPrimaryContainer: Color(0xFF002204),
      secondary: Color(0xFF52634F),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFD5E8CF),
      onSecondaryContainer: Color(0xFF111F0F),
      tertiary: Color(0xFF38656A),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFBCEBF0),
      onTertiaryContainer: Color(0xFF002023),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFCFDF6),
      onBackground: Color(0xFF1A1C19),
      surface: Color(0xFFFCFDF6),
      onSurface: Color(0xFF1A1C19),
      surfaceVariant: Color(0xFFDEE5D8),
      onSurfaceVariant: Color(0xFF424940),
      outline: Color(0xFF72796F),
      onInverseSurface: Color(0xFFF0F1EB),
      inverseSurface: Color(0xFF2F312D),
      inversePrimary: Color(0xFF78DC77),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF006E1C),
      // outlineVariant: Color(0xFFC2C9BD),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF78DC77),
      onPrimary: Color(0xFF00390A),
      primaryContainer: Color(0xFF005313),
      onPrimaryContainer: Color(0xFF94F990),
      secondary: Color(0xFFBACCB3),
      onSecondary: Color(0xFF253423),
      secondaryContainer: Color(0xFF3B4B38),
      onSecondaryContainer: Color(0xFFD5E8CF),
      tertiary: Color(0xFFA0CFD4),
      onTertiary: Color(0xFF00363B),
      tertiaryContainer: Color(0xFF1F4D52),
      onTertiaryContainer: Color(0xFFBCEBF0),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF1A1C19),
      onBackground: Color(0xFFE2E3DD),
      surface: Color(0xFF1A1C19),
      onSurface: Color(0xFFE2E3DD),
      surfaceVariant: Color(0xFF424940),
      onSurfaceVariant: Color(0xFFC2C9BD),
      outline: Color(0xFF8C9388),
      onInverseSurface: Color(0xFF1A1C19),
      inverseSurface: Color(0xFFE2E3DD),
      inversePrimary: Color(0xFF006E1C),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF78DC77),
      // outlineVariant: Color(0xFF424940),
      // scrim: Color(0xFF000000),
    ),
  );

  static const lightGreen = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF3E6A00),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFB9F474),
      onPrimaryContainer: Color(0xFF0F2000),
      secondary: Color(0xFF576249),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFDBE7C8),
      onSecondaryContainer: Color(0xFF151E0B),
      tertiary: Color(0xFF386663),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFBBECE8),
      onTertiaryContainer: Color(0xFF00201E),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFDFCF5),
      onBackground: Color(0xFF1B1C18),
      surface: Color(0xFFFDFCF5),
      onSurface: Color(0xFF1B1C18),
      surfaceVariant: Color(0xFFE1E4D5),
      onSurfaceVariant: Color(0xFF44483D),
      outline: Color(0xFF75796C),
      onInverseSurface: Color(0xFFF2F1E9),
      inverseSurface: Color(0xFF30312C),
      inversePrimary: Color(0xFF9ED75B),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF3E6A00),
      // outlineVariant: Color(0xFFC5C8BA),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF9ED75B),
      onPrimary: Color(0xFF1E3700),
      primaryContainer: Color(0xFF2E4F00),
      onPrimaryContainer: Color(0xFFB9F474),
      secondary: Color(0xFFBFCBAD),
      onSecondary: Color(0xFF2A331E),
      secondaryContainer: Color(0xFF404A33),
      onSecondaryContainer: Color(0xFFDBE7C8),
      tertiary: Color(0xFFA0D0CC),
      onTertiary: Color(0xFF003735),
      tertiaryContainer: Color(0xFF1F4E4B),
      onTertiaryContainer: Color(0xFFBBECE8),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF1B1C18),
      onBackground: Color(0xFFE3E3DB),
      surface: Color(0xFF1B1C18),
      onSurface: Color(0xFFE3E3DB),
      surfaceVariant: Color(0xFF44483D),
      onSurfaceVariant: Color(0xFFC5C8BA),
      outline: Color(0xFF8E9285),
      onInverseSurface: Color(0xFF1B1C18),
      inverseSurface: Color(0xFFE3E3DB),
      inversePrimary: Color(0xFF3E6A00),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF9ED75B),
      // outlineVariant: Color(0xFF44483D),
      // scrim: Color(0xFF000000),
    ),
  );

  static const lime = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF5B6300),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFDDED49),
      onPrimaryContainer: Color(0xFF1A1D00),
      secondary: Color(0xFF5E6044),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFE4E5C1),
      onSecondaryContainer: Color(0xFF1B1D07),
      tertiary: Color(0xFF3C665A),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFBEECDC),
      onTertiaryContainer: Color(0xFF002019),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFCFFDE),
      onBackground: Color(0xFF181E00),
      surface: Color(0xFFFCFFDE),
      onSurface: Color(0xFF181E00),
      surfaceVariant: Color(0xFFE5E3D2),
      onSurfaceVariant: Color(0xFF47483B),
      outline: Color(0xFF787869),
      onInverseSurface: Color(0xFFE6FB88),
      inverseSurface: Color(0xFF2B3400),
      inversePrimary: Color(0xFFC1D02C),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF5B6300),
      // outlineVariant: Color(0xFFC8C7B7),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFC1D02C),
      onPrimary: Color(0xFF2F3300),
      primaryContainer: Color(0xFF444B00),
      onPrimaryContainer: Color(0xFFDDED49),
      secondary: Color(0xFFC7C9A6),
      onSecondary: Color(0xFF30321A),
      secondaryContainer: Color(0xFF46492E),
      onSecondaryContainer: Color(0xFFE4E5C1),
      tertiary: Color(0xFFA2D0C1),
      onTertiary: Color(0xFF07372D),
      tertiaryContainer: Color(0xFF234E43),
      onTertiaryContainer: Color(0xFFBEECDC),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF181E00),
      onBackground: Color(0xFFD8ED7C),
      surface: Color(0xFF181E00),
      onSurface: Color(0xFFD8ED7C),
      surfaceVariant: Color(0xFF47483B),
      onSurfaceVariant: Color(0xFFC8C7B7),
      outline: Color(0xFF929282),
      onInverseSurface: Color(0xFF181E00),
      inverseSurface: Color(0xFFD8ED7C),
      inversePrimary: Color(0xFF5B6300),
      shadow: Colors.black12,
      surfaceTint: Color(0xFFC1D02C),
      // outlineVariant: Color(0xFF47483B),
      // scrim: Color(0xFF000000),
    ),
  );

  static const yellow = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF686000),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFF3E569),
      onPrimaryContainer: Color(0xFF1F1C00),
      secondary: Color(0xFF635F41),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFEAE3BD),
      onSecondaryContainer: Color(0xFF1F1C05),
      tertiary: Color(0xFF406653),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFC2ECD3),
      onTertiaryContainer: Color(0xFF002114),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFFFBFF),
      onBackground: Color(0xFF1D1C16),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF1D1C16),
      surfaceVariant: Color(0xFFE8E2D0),
      onSurfaceVariant: Color(0xFF49473A),
      outline: Color(0xFF7A7768),
      onInverseSurface: Color(0xFFF5F0E7),
      inverseSurface: Color(0xFF32302A),
      inversePrimary: Color(0xFFD6C950),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF686000),
      // outlineVariant: Color(0xFFCBC7B5),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFD6C950),
      onPrimary: Color(0xFF363100),
      primaryContainer: Color(0xFF4E4800),
      onPrimaryContainer: Color(0xFFF3E569),
      secondary: Color(0xFFCEC7A3),
      onSecondary: Color(0xFF343117),
      secondaryContainer: Color(0xFF4B472B),
      onSecondaryContainer: Color(0xFFEAE3BD),
      tertiary: Color(0xFFA6D0B8),
      onTertiary: Color(0xFF103726),
      tertiaryContainer: Color(0xFF284E3C),
      onTertiaryContainer: Color(0xFFC2ECD3),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF1D1C16),
      onBackground: Color(0xFFE7E2D9),
      surface: Color(0xFF1D1C16),
      onSurface: Color(0xFFE7E2D9),
      surfaceVariant: Color(0xFF49473A),
      onSurfaceVariant: Color(0xFFCBC7B5),
      outline: Color(0xFF959181),
      onInverseSurface: Color(0xFF1D1C16),
      inverseSurface: Color(0xFFE7E2D9),
      inversePrimary: Color(0xFF686000),
      shadow: Colors.black12,
      surfaceTint: Color(0xFFD6C950),
      // outlineVariant: Color(0xFF49473A),
      // scrim: Color(0xFF000000),
    ),
  );

  static const amber = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF785900),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFDF9E),
      onPrimaryContainer: Color(0xFF261A00),
      secondary: Color(0xFF6B5D3F),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFF5E0BB),
      onSecondaryContainer: Color(0xFF241A04),
      tertiary: Color(0xFF4A6547),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFCCEBC4),
      onTertiaryContainer: Color(0xFF072109),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFFFBFF),
      onBackground: Color(0xFF1E1B16),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF1E1B16),
      surfaceVariant: Color(0xFFEDE1CF),
      onSurfaceVariant: Color(0xFF4D4639),
      outline: Color(0xFF7F7667),
      onInverseSurface: Color(0xFFF7EFE7),
      inverseSurface: Color(0xFF33302A),
      inversePrimary: Color(0xFFFABD00),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF785900),
      // outlineVariant: Color(0xFFD0C5B4),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFD6C950),
      onPrimary: Color(0xFF363100),
      primaryContainer: Color(0xFF4E4800),
      onPrimaryContainer: Color(0xFFF3E569),
      secondary: Color(0xFFCEC7A3),
      onSecondary: Color(0xFF343117),
      secondaryContainer: Color(0xFF4B472B),
      onSecondaryContainer: Color(0xFFEAE3BD),
      tertiary: Color(0xFFA6D0B8),
      onTertiary: Color(0xFF103726),
      tertiaryContainer: Color(0xFF284E3C),
      onTertiaryContainer: Color(0xFFC2ECD3),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF1D1C16),
      onBackground: Color(0xFFE7E2D9),
      surface: Color(0xFF1D1C16),
      onSurface: Color(0xFFE7E2D9),
      surfaceVariant: Color(0xFF49473A),
      onSurfaceVariant: Color(0xFFCBC7B5),
      outline: Color(0xFF959181),
      onInverseSurface: Color(0xFF1D1C16),
      inverseSurface: Color(0xFFE7E2D9),
      inversePrimary: Color(0xFF686000),
      shadow: Colors.black12,
      surfaceTint: Color(0xFFD6C950),
      // outlineVariant: Color(0xFF49473A),
      // scrim: Color(0xFF000000),
    ),
  );

  static const orange = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF8B5000),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFDCBE),
      onPrimaryContainer: Color(0xFF2C1600),
      secondary: Color(0xFF725A42),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFFDCBE),
      onSecondaryContainer: Color(0xFF291806),
      tertiary: Color(0xFF58633A),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFDCE8B4),
      onTertiaryContainer: Color(0xFF161E01),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFFFBFF),
      onBackground: Color(0xFF201B16),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF201B16),
      surfaceVariant: Color(0xFFF2DFD1),
      onSurfaceVariant: Color(0xFF51453A),
      outline: Color(0xFF837468),
      onInverseSurface: Color(0xFFFAEFE7),
      inverseSurface: Color(0xFF352F2B),
      inversePrimary: Color(0xFFFFB870),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF8B5000),
      // outlineVariant: Color(0xFFD5C3B5),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFB870),
      onPrimary: Color(0xFF4A2800),
      primaryContainer: Color(0xFF693C00),
      onPrimaryContainer: Color(0xFFFFDCBE),
      secondary: Color(0xFFE1C1A4),
      onSecondary: Color(0xFF402C18),
      secondaryContainer: Color(0xFF59422C),
      onSecondaryContainer: Color(0xFFFFDCBE),
      tertiary: Color(0xFFC0CC9A),
      onTertiary: Color(0xFF2B3410),
      tertiaryContainer: Color(0xFF414B24),
      onTertiaryContainer: Color(0xFFDCE8B4),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF201B16),
      onBackground: Color(0xFFEBE0D9),
      surface: Color(0xFF201B16),
      onSurface: Color(0xFFEBE0D9),
      surfaceVariant: Color(0xFF51453A),
      onSurfaceVariant: Color(0xFFD5C3B5),
      outline: Color(0xFF9D8E81),
      onInverseSurface: Color(0xFF201B16),
      inverseSurface: Color(0xFFEBE0D9),
      inversePrimary: Color(0xFF8B5000),
      shadow: Colors.black12,
      surfaceTint: Color(0xFFFFB870),
      // outlineVariant: Color(0xFF51453A),
      // scrim: Color(0xFF000000),
    ),
  );

  static const deepOrange = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFFB02F00),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFDBD1),
      onPrimaryContainer: Color(0xFF3B0900),
      secondary: Color(0xFF77574E),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFFDBD1),
      onSecondaryContainer: Color(0xFF2C150F),
      tertiary: Color(0xFF6C5D2F),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFF5E1A7),
      onTertiaryContainer: Color(0xFF231B00),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFFFBFF),
      onBackground: Color(0xFF201A18),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF201A18),
      surfaceVariant: Color(0xFFF5DED8),
      onSurfaceVariant: Color(0xFF53433F),
      outline: Color(0xFF85736E),
      onInverseSurface: Color(0xFFFBEEEB),
      inverseSurface: Color(0xFF362F2D),
      inversePrimary: Color(0xFFFFB5A0),
      shadow: Colors.black12,
      surfaceTint: Color(0xFFB02F00),
      // outlineVariant: Color(0xFFD8C2BC),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFB5A0),
      onPrimary: Color(0xFF5F1500),
      primaryContainer: Color(0xFF862200),
      onPrimaryContainer: Color(0xFFFFDBD1),
      secondary: Color(0xFFE7BDB2),
      onSecondary: Color(0xFF442A22),
      secondaryContainer: Color(0xFF5D4037),
      onSecondaryContainer: Color(0xFFFFDBD1),
      tertiary: Color(0xFFD8C58D),
      onTertiary: Color(0xFF3B2F05),
      tertiaryContainer: Color(0xFF534619),
      onTertiaryContainer: Color(0xFFF5E1A7),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF201A18),
      onBackground: Color(0xFFEDE0DC),
      surface: Color(0xFF201A18),
      onSurface: Color(0xFFEDE0DC),
      surfaceVariant: Color(0xFF53433F),
      onSurfaceVariant: Color(0xFFD8C2BC),
      outline: Color(0xFFA08C87),
      onInverseSurface: Color(0xFF201A18),
      inverseSurface: Color(0xFFEDE0DC),
      inversePrimary: Color(0xFFB02F00),
      shadow: Colors.black12,
      surfaceTint: Color(0xFFFFB5A0),
      // outlineVariant: Color(0xFF53433F),
      // scrim: Color(0xFF000000),
    ),
  );

  static const brown = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF9A4522),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFFFDBCF),
      onPrimaryContainer: Color(0xFF380D00),
      secondary: Color(0xFF77574C),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFFFDBCF),
      onSecondaryContainer: Color(0xFF2C160D),
      tertiary: Color(0xFF695E2F),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFF2E2A8),
      onTertiaryContainer: Color(0xFF211B00),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFFFBFF),
      onBackground: Color(0xFF201A18),
      surface: Color(0xFFFFFBFF),
      onSurface: Color(0xFF201A18),
      surfaceVariant: Color(0xFFF5DED6),
      onSurfaceVariant: Color(0xFF53433E),
      outline: Color(0xFF85736D),
      onInverseSurface: Color(0xFFFBEEEA),
      inverseSurface: Color(0xFF362F2C),
      inversePrimary: Color(0xFFFFB59A),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF9A4522),
      // outlineVariant: Color(0xFFD8C2BB),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFFFFB59A),
      onPrimary: Color(0xFF5B1B00),
      primaryContainer: Color(0xFF7B2E0D),
      onPrimaryContainer: Color(0xFFFFDBCF),
      secondary: Color(0xFFE7BEAF),
      onSecondary: Color(0xFF442A20),
      secondaryContainer: Color(0xFF5D4035),
      onSecondaryContainer: Color(0xFFFFDBCF),
      tertiary: Color(0xFFD5C68E),
      onTertiary: Color(0xFF393005),
      tertiaryContainer: Color(0xFF50471A),
      onTertiaryContainer: Color(0xFFF2E2A8),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF201A18),
      onBackground: Color(0xFFEDE0DC),
      surface: Color(0xFF201A18),
      onSurface: Color(0xFFEDE0DC),
      surfaceVariant: Color(0xFF53433E),
      onSurfaceVariant: Color(0xFFD8C2BB),
      outline: Color(0xFFA08D86),
      onInverseSurface: Color(0xFF201A18),
      inverseSurface: Color(0xFFEDE0DC),
      inversePrimary: Color(0xFF9A4522),
      shadow: Colors.black12,
      surfaceTint: Color(0xFFFFB59A),
      // outlineVariant: Color(0xFF53433E),
      // scrim: Color(0xFF000000),
    ),
  );

  static const blueGrey = Material3Schemes(
    light: ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xFF006783),
      onPrimary: Color(0xFFFFFFFF),
      primaryContainer: Color(0xFFBDE9FF),
      onPrimaryContainer: Color(0xFF001F2A),
      secondary: Color(0xFF4D616C),
      onSecondary: Color(0xFFFFFFFF),
      secondaryContainer: Color(0xFFD0E6F2),
      onSecondaryContainer: Color(0xFF081E27),
      tertiary: Color(0xFF5D5B7D),
      onTertiary: Color(0xFFFFFFFF),
      tertiaryContainer: Color(0xFFE3DFFF),
      onTertiaryContainer: Color(0xFF191836),
      error: Color(0xFFBA1A1A),
      errorContainer: Color(0xFFFFDAD6),
      onError: Color(0xFFFFFFFF),
      onErrorContainer: Color(0xFF410002),
      background: Color(0xFFFBFCFE),
      onBackground: Color(0xFF191C1E),
      surface: Color(0xFFFBFCFE),
      onSurface: Color(0xFF191C1E),
      surfaceVariant: Color(0xFFDCE4E9),
      onSurfaceVariant: Color(0xFF40484C),
      outline: Color(0xFF70787D),
      onInverseSurface: Color(0xFFEFF1F3),
      inverseSurface: Color(0xFF2E3132),
      inversePrimary: Color(0xFF65D3FF),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF006783),
      // outlineVariant: Color(0xFFC0C8CD),
      // scrim: Color(0xFF000000),
    ),
    dark: ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xFF65D3FF),
      onPrimary: Color(0xFF003546),
      primaryContainer: Color(0xFF004D64),
      onPrimaryContainer: Color(0xFFBDE9FF),
      secondary: Color(0xFFB4CAD6),
      onSecondary: Color(0xFF1F333C),
      secondaryContainer: Color(0xFF354A53),
      onSecondaryContainer: Color(0xFFD0E6F2),
      tertiary: Color(0xFFC6C2EA),
      onTertiary: Color(0xFF2E2D4D),
      tertiaryContainer: Color(0xFF454364),
      onTertiaryContainer: Color(0xFFE3DFFF),
      error: Color(0xFFFFB4AB),
      errorContainer: Color(0xFF93000A),
      onError: Color(0xFF690005),
      onErrorContainer: Color(0xFFFFDAD6),
      background: Color(0xFF191C1E),
      onBackground: Color(0xFFE1E2E4),
      surface: Color(0xFF191C1E),
      onSurface: Color(0xFFE1E2E4),
      surfaceVariant: Color(0xFF40484C),
      onSurfaceVariant: Color(0xFFC0C8CD),
      outline: Color(0xFF8A9297),
      onInverseSurface: Color(0xFF191C1E),
      inverseSurface: Color(0xFFE1E2E4),
      inversePrimary: Color(0xFF006783),
      shadow: Colors.black12,
      surfaceTint: Color(0xFF65D3FF),
      // outlineVariant: Color(0xFF40484C),
      // scrim: Color(0xFF000000),
    ),
  );

  static const List<Material3Schemes> styles = <Material3Schemes>[
    red,
    pink,
    purple,
    deepPurple,
    indigo,
    blue,
    lightBlue,
    cyan,
    teal,
    green,
    lightGreen,
    lime,
    yellow,
    amber,
    orange,
    deepOrange,
    brown,
    //blueGrey,
  ];
}
