name: Firebase configuration

on:
  workflow_call:
    secrets: inherit

runs:
    using: "composite"
    steps:
      - name: Create Firebase Configuration Files forn Native / Flutter
        env:
            GOOGLE_SERVICES_ANDROID: ${{ secrets.GOOGLE_SERVICES_ANDROID_JSON }}
            GOOGLE_SERVICES_IOS: ${{ secrets.GOOGLE_SERVICES_IOS_PLIST }}
            FIREBASE_APP_ID_IOS: ${{ secrets.FIREBASE_APP_ID_IOS_JSON }}
            FIREBASE_OPTIONS_DART: ${{ secrets.FIREBASE_OPTIONS_DART }}
        run: |
            echo Android google_services.json
            echo "$GOOGLE_SERVICES_ANDROID_JSON" > google-services.json.b64
            base64 -d -i google-services.json.b64 > android/app/google-services.json
            echo iOS google_services.json
            echo "$GOOGLE_SERVICES_IOS" > GoogleService-Info.plist.b64
            base64 -d -i GoogleService-Info.plist.b64 > ios/Runner/GoogleService-Info.plist
            echo iOS Firebase APP ID
            echo "$FIREBASE_APP_ID_IOS" > firebase_app_id_file.json.b64
            base64 -d -i firebase_app_id_file.json.b64 > ios/firebase_app_id_file.json
            echo Firebase .dart file
            echo "$FIREBASE_OPTIONS_DART" > FIREBASE_OPTIONS_DART.dart.b64
            base64 -d -i FIREBASE_OPTIONS_DART.dart.b64 > lib/firebase_options.dart