// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema8 extends i0.VersionedSchema {
  Schema8({required super.database}) : super(version: 8);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    country,
    affiliationLink,
    amiibo,
    amiiboUserPreferences,
    amiiboImages,
    amiiboBundle,
    amiiboBundleUserPreferences,
    amiiboBundleImages,
  ];
  late final Shape0 country = Shape0(
    source: i0.VersionedTable(
      entityName: 'country',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 affiliationLink = Shape1(
    source: i0.VersionedTable(
      entityName: 'affiliation_link',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'FOREIGN KEY(country_code)REFERENCES country(code)',
        'UNIQUE(country_code)',
      ],
      columns: [_column_4, _column_5, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 amiibo = Shape2(
    source: i0.VersionedTable(
      entityName: 'amiibo',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 amiiboUserPreferences = Shape3(
    source: i0.VersionedTable(
      entityName: 'amiibo_user_preferences',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'FOREIGN KEY(amiibo_key)REFERENCES amiibo("key")',
        'UNIQUE(amiibo_key)',
      ],
      columns: [_column_19, _column_20, _column_21, _column_22, _column_23],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 amiiboImages = Shape4(
    source: i0.VersionedTable(
      entityName: 'amiibo_images',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'FOREIGN KEY(amiibo_key)REFERENCES amiibo("key")ON DELETE CASCADE',
      ],
      columns: [_column_4, _column_20, _column_24, _column_25],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 amiiboBundle = Shape5(
    source: i0.VersionedTable(
      entityName: 'amiibo_bundle',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'FOREIGN KEY(amiibo_key)REFERENCES amiibo("key")ON DELETE CASCADE',
      ],
      columns: [_column_26, _column_20, _column_12, _column_27],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 amiiboBundleUserPreferences = Shape6(
    source: i0.VersionedTable(
      entityName: 'amiibo_bundle_user_preferences',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'FOREIGN KEY(amiibo_bundle_id)REFERENCES amiibo_bundle(id)',
        'UNIQUE(amiibo_bundle_id)',
      ],
      columns: [_column_4, _column_28, _column_21, _column_22],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 amiiboBundleImages = Shape7(
    source: i0.VersionedTable(
      entityName: 'amiibo_bundle_images',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'FOREIGN KEY(amiibo_bundle_id)REFERENCES amiibo_bundle(id)ON DELETE CASCADE',
      ],
      columns: [_column_4, _column_28, _column_24, _column_25],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get code =>
      columnsByName['code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get en =>
      columnsByName['en']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get es =>
      columnsByName['es']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fr =>
      columnsByName['fr']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'en',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'es',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'fr',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get countryCode =>
      columnsByName['country_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get amazon =>
      columnsByName['amazon']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'country_code',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'amazon',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get key =>
      columnsByName['key']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get amiiboSeries =>
      columnsByName['amiiboSeries']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get character =>
      columnsByName['character']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gameSeries =>
      columnsByName['gameSeries']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get au =>
      columnsByName['au']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get eu =>
      columnsByName['eu']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get jp =>
      columnsByName['jp']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get na =>
      columnsByName['na']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get cardNumber =>
      columnsByName['cardNumber']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'amiiboSeries',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'character',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'gameSeries',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'au',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'eu',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'jp',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'na',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: '',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cardNumber',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: '',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get key =>
      columnsByName['key']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get amiiboKey =>
      columnsByName['amiibo_key']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get boxed =>
      columnsByName['boxed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get opened =>
      columnsByName['opened']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get wishlist =>
      columnsByName['wishlist']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'key',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'amiibo_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'boxed',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'opened',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'wishlist',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get amiiboKey =>
      columnsByName['amiibo_key']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get filePath =>
      columnsByName['file_path']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'create_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'file_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get amiiboKey =>
      columnsByName['amiibo_key']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get quantity =>
      columnsByName['quantity']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY',
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'quantity',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1',
      defaultValue: const i1.CustomExpression('1'),
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get amiiboBundleId =>
      columnsByName['amiibo_bundle_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get boxed =>
      columnsByName['boxed']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get opened =>
      columnsByName['opened']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'amiibo_bundle_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get amiiboBundleId =>
      columnsByName['amiibo_bundle_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get filePath =>
      columnsByName['file_path']! as i1.GeneratedColumn<String>;
}

i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 7:
        final schema = Schema8(database: database);
        final migrator = i1.Migrator(database, schema);
        await from7To8(migrator, schema);
        return 8;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from7To8: from7To8),
);
